version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        ports:
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=fabian
            - RABBITMQ_DEFAULT_PASS=fabian
        networks:
            - web
        deploy:
            placement:
                constraints: [node.role == manager]
        volumes:
            - /var/run/docker.sock:/docker.sock

    flask:
        image: 192.168.1.76:5000/api
        build:
            context: .
            dockerfile: ./api/Dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
        ports:
            - 8000:8000 #does not need to be exposed in dockerfile?
        environment:
            - SERVICE_PORTS=8000
        networks:
            - web
        deploy:
            placement:
                constraints: [node.role == manager]

    worker:
        image: 192.168.1.76:5000/celery-queue
        build:
            context: .
            dockerfile: ./celery-queue/Dockerfile
        links:
            - rabbit
            - redis
        depends_on:
            - rabbit
            - redis
        networks:
            - web    
       
    redis:
        hostname: redis
        image: "redis:alpine"
        networks:
            - web   
        ports:
            - 6379:6379
        deploy:
            placement:
                constraints: [node.role == manager]
        

            
#    proxy:
#        image: dockercloud/haproxy
#        depends_on:
#            - flask
#        environment:
#            - BALANCE=leastconn
#        volumes:
#            - /var/run/docker.sock:/var/run/docker.sock
#        ports:
#            - 80:80
#        networks:
#            - web
#        deploy:
#            placement:
#                constraints: [node.role == manager]
networks:
  web:
    driver: overlay
    
        
